CAUSOLDOUTMEN/Diareat_backend

src/main/java/com/diareat/diareat/food/controller/FoodController.java
src/main/java/com/diareat/diareat/food/dto/CreateFoodDto.java
src/main/java/com/diareat/diareat/food/dto/UpdateFavoriteFoodDto.java
src/main/java/com/diareat/diareat/food/dto/UpdateFoodDto.java
src/main/java/com/diareat/diareat/food/repository/FavoriteFoodRepository.java
src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/main/java/com/diareat/diareat/util/api/ResponseCode.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

https://github.com/CAUSOLDOUTMEN/Diareat_backend/pull/45
* 음식/즐찾음식 수정 Dto에 userId 속성 추가
* CreateFoodDto에 date 속성 추가 (특정 날짜의 음식 조회 데이터 캐싱 일관성 부여)
* 음식/즐찾음식 삭제 기능의 validate 함수 추가적인 유효성검사 적용 (유저가 이 음식을 "소유"하고 있는 관계가 맞는지 판정하는 과정 추가)
* 이를 위해 음식/즐찾음식 삭제(해제) 요청에 클라가 RequestHeader 에 userId 속성 담아 서버로 보내는 제약 추가
* FoodService 캐싱 적용
* 음식/즐찾음식 생성인데 왜 CacheEvict인가요? -> 메모리는 새로 추가된 상황을 모르고 있기 때문에

Feat: RedisCache를 통한 캐싱 적용 (#44) [잔여 부분]

---

src/main/java/com/diareat/diareat/auth/dto/KakaoAccount.java
src/main/java/com/diareat/diareat/auth/dto/KakaoProfile.java
src/main/java/com/diareat/diareat/auth/dto/KakaoProperties.java
src/main/java/com/diareat/diareat/auth/dto/KakaoUserInfoResponse.java
src/main/java/com/diareat/diareat/auth/service/KakaoAuthService.java

* 타임리프를 통해 클라이언트 입장에서의 카카오로그인을 실제로 시도
* 프사 url에 대해 접근 시 return 과정에서 NullPointerException 발생
* 확인 결과 서버에 accessToken을 전송했을 때 반환 JSON은 아래와 같았음
```java
{
"id": Long,
"connected_at": "string",
"properties": {
"nickname": "string",
"profile_image": "string",
"thumbnail_image": "string"
},
"kakao_account": {
"profile_nickname_needs_agreement": false,
"profile_image_needs_agreement": false,
"profile": {
"nickname": "string",
"thumbnail_image_url": "string",
"profile_image_url": "string",
"is_default_image": false
}
}
}
```
* 초기 설정한 Dto는 카멜 케이스였고, 카카오 서버에서 반환하는 JSON은 스네이크 케이스
* getter에서 표현의 차이로 미스매칭이 발생
* Dto를 모두 스네이크 케이스로 통일
* /api/auth/join 실행 시 성공적으로 동작하는 것을 확인함
```java
{
"header": {
"code": 200,
"message": "SUCCESS"
},
"data": {
"1": "string"
},
"msg": "사용자 생성 성공"
}
```

Fix: 카카오로그인 에러 수정 (#51)

---

build.gradle
k8s/manifest.yaml
src/main/java/com/diareat/diareat/config/WebSecurityConfig.java
src/main/resources/application.properties

Feat: 헬스 체크 활성화

---

k8s/manifest.yaml
src/main/java/com/diareat/diareat/food/dto/ResponseNutritionSumByDateDto.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java

-[x] 날짜별 영양소 섭취량 로직 중, 누락된 기준 영양소 수정
-[x] 지나치게 느린 초기 구동으로 인해 CPU 할당량 소폭 증가

Fix: 누락된 기준 영양소 수정 (#60)

---

src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java

Fix: Cache에서 key값 타입 수정

---

src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java

* 오후에 발생한 문제와 동일하게, ResponseDto에 LocalDate/Time 타입이 존재할 경우 직렬화 오류 발생
* 임시 주석처리

Fix: ResponseFoodDto Date/Time 타입 주석처리 (#66)

---

src/main/java/com/diareat/diareat/food/domain/Food.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

Fix: 테이블의 칼럼 명과 직접 매핑

---

src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

hotfix: sort by 인자 수정 (#76)

---

src/main/java/com/diareat/diareat/food/controller/FoodController.java
src/main/java/com/diareat/diareat/food/dto/ResponseAnalysisDto.java
src/main/java/com/diareat/diareat/food/dto/ResponseFavoriteFoodDto.java
src/main/java/com/diareat/diareat/food/dto/ResponseFoodRankDto.java
src/main/java/com/diareat/diareat/food/dto/ResponseScoreBestWorstDto.java
src/main/java/com/diareat/diareat/food/dto/ResponseSimpleFoodDto.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/main/java/com/diareat/diareat/user/dto/response/ResponseSimpleUserDto.java
src/main/java/com/diareat/diareat/user/service/UserService.java
src/main/java/com/diareat/diareat/util/MessageUtil.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
src/test/java/com/diareat/diareat/controller/UserControllerTest.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

* 음식 수정 및 삭제 시 해당 음식의 날짜에 해당하는 음식 Dto 캐시에서 삭제하는 기능 누락
* 이를 위해 Controller에서 클라이언트가 제공하는 yy-mm-dd 값을 활용
* ResponseSimpleDto 더미 영양점수 삭제 (클라이언트와 협의 완료)
* user 패키지에 주요 Dto 기본생성자 추가
* 반복되는 addedTime 문자열 MessageUtil에서 단일 관리
* 불필요한 import 정리 및 테스트코드 변경

Fix: Redis 캐시 일관성 손실 문제 해결 (#84)

---

src/main/java/com/diareat/diareat/food/service/FoodService.java

* 즐겨찾기에 음식 추가 기능은 현재 날짜 음식 조회 캐싱데이터의 초기화를 필요로 하는데, 즐겨찾기 관련 응답 데이터의 key에 date 속성이 들어갈 수 없어, 현재 날짜 음식 조회의 캐싱을 배제
* 기타 잘못된 RedisCache value 표기 수정

Fix: 캐싱 value 일부 수정 (#92)

---

src/main/java/com/diareat/diareat/food/service/FoodService.java

* 두 키 사이에 공백이 끼어 있어 캐시 일관성이 위반되는 버그인 것으로 확인되어 조치함
* 만약 지속적으로 문제 발생 시 즐겨찾기음식 관련 기능 제외 FoodService에선 캐싱 배제

:ambulance: Fix: 오늘의영양 key 공백 끼어있는 상황 수정 (#94)

---

src/main/java/com/diareat/diareat/food/controller/FoodController.java
src/main/java/com/diareat/diareat/food/dto/CreateFoodFromFavoriteFoodDto.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

- 즐찾 음식으로부터 음식 생성 메소드 구현
- 테스트 코드 작성 및 통과 확인
- 새로운 api endpoint: /food/favorite/createfrom
- 새로운 dto: CreateFoodFromFavoriteFoodDto

Feat: 즐찾 음식으로부터 음식 생성 메소드 구현 (#96)

---

src/main/java/com/diareat/diareat/food/controller/FoodController.java
src/main/java/com/diareat/diareat/food/repository/FoodRepository.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

- LocalDate.now()로 인해 서버쪽에서 시간 의존성 발생
- 테스트 코드가 일관된 결과를 도출하지 않음
- 클라이언트에서 날짜를 parameter로 받고, 이를 통해 LocalDate 객체 생성 방법으로 변경

Fix: 서버에서의 시간 의존성 제거

---

src/main/java/com/diareat/diareat/user/repository/FollowRepository.java
src/main/java/com/diareat/diareat/user/service/UserService.java
src/test/java/com/diareat/diareat/service/UserServiceTest.java

* 팔로우 기능 버그 수정
* UserService 각 메서드마다 서버에서 확인할 수 있도록 로그 추가

Fix: 서비스 주요 시점 로그 추가 및 팔로우 관련 버그 수정 (#106)

---

src/main/java/com/diareat/diareat/food/domain/FavoriteFood.java
src/main/java/com/diareat/diareat/food/domain/Food.java
src/main/java/com/diareat/diareat/food/repository/FavoriteFoodRepository.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/main/java/com/diareat/diareat/user/dto/request/JoinUserDto.java
src/main/java/com/diareat/diareat/user/dto/request/UpdateUserDto.java
src/main/java/com/diareat/diareat/user/dto/request/UpdateUserNutritionDto.java

* 음식 -> 즐겨찾는 음식: 일대 일
* 즐겨찾는 음식 -> 음식: 일대 일
* 음식 -> 즐겨찾는 음식: 다대 일 (단, 실제로는 일대 일처럼 운용하도록 예외처리)
* 즐겨찾는 음식 -> 음식: 일대 다 (즐겨찾는 음식으로부터 여러 개의 음식이 태어날 수 있다는 점에서 관계의 주인을 즐찾음식으로 설정함)
* FavoriteFoodRepository의 existsByFoodId 삭제 (Food.isFavorite()을 통해 중복 즐찾 여부를 판정하도록 수정)
* 관계의 주인이 즐겨찾기로 명확하게 정해졌으며, food.setFavoriteFood()는 즐겨찾기로부터 음식을 창조하는 경우와 최초로 음식을 즐겨찾기에 등록하는 경우 2가지에서 사용

Fix: 즐겨찾기 버그 수정을 위한 음식-즐겨찾는음식 연관관계 개편 (#114)

---

src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

* FavoriteFood가 연관관계의 주인이나, FavoriteFood 소멸 시 이를 바라보던 자식 Food 객체가 null을 바라도록 처리되어야 함
* 허나 의도대로 처리되지 않아 직접 setter로 명시적으로 음식들의 즐찾여부를 해제

Fix: 즐찾 해제 시 자식 음식객체 연쇄삭제 명시적으로 추가 (#114)

---

src/main/java/com/diareat/diareat/food/dto/ResponseAnalysisDto.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

- 기존 로직은 날짜 없으면 생략하고 다른 날의 음식들을 마저 반환
- 해당 날짜에 음식이 없으면 0을 반환하도록 수정
- 한달간의 음식의 경우, 1주 단위로 묶어 값을 합한 후, 총 4개의 원소를 반환하도록 수정

Feat: 일별 음식에서 해당 날짜 없으면 0 반환 및 한 주 단위로 묶어 데이터 반환 (#120)

---

src/main/java/com/diareat/diareat/auth/component/JwtTokenProvider.java
src/main/java/com/diareat/diareat/auth/service/CustomUserDetailService.java
src/main/java/com/diareat/diareat/user/domain/User.java
src/main/java/com/diareat/diareat/user/dto/request/UpdateUserDto.java
src/main/java/com/diareat/diareat/user/service/UserService.java
src/main/java/com/diareat/diareat/util/MessageUtil.java
src/test/java/com/diareat/diareat/controller/UserControllerTest.java
src/test/java/com/diareat/diareat/service/UserServiceTest.java

* 기준섭취량 자동계산 여부를 나타내는 변수가 swagger 나타나고 있지 않음
* boolean 자료형을 int(0, 1)로 수정함
* 관련 로직 및 테스트코드 수정
* 현재 토큰을 활용하고 있진 않으나, jwt 토큰 관련 설정 일부 수정

Fix: 기준섭취량 자동계산 boolean 누락된 버그 수정 (#122)

---

src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java

* ResponseFoodDto에 시간 값이 누락되어 반영함

Fix: ResponseFoodDto에 생성시간 누락 반영 (#122)

---

src/main/java/com/diareat/diareat/food/dto/ResponseFoodDto.java
src/main/java/com/diareat/diareat/food/service/FoodService.java
src/test/java/com/diareat/diareat/controller/FoodControllerTest.java
src/test/java/com/diareat/diareat/service/FoodServiceTest.java

- 현재 날짜를 포함해서 그래프 데이터를 주도록 수정
- LocalTime 객체 대신 Hour, Minute으로 명확하게 시간 정보를 주도록 수정

Fix: LocalTime 자료형 분해 및 Analysis 수정

---

src/main/java/com/diareat/diareat/user/domain/User.java

* 기준섭취량 자동계산 여부에 체크하면 유저의 기준섭취량이 기준에 따라 자동으로 배정(초기화)되어야 함
* 누락된 로직으로 인해 반영되지 않던 버그 수정

Fix: 기준섭취량 자동계산 옵션 발동되지 않던 버그 수정 (#122)

---

src/main/java/com/diareat/diareat/food/service/FoodService.java

* 현재 음식명 중복 등록에 대한 예외처리가 작동 중
* 며칠 전 등록한 음식명이랑 같다는 이유로 거부당하면 사용자 경험에 좋지 않을 것이며, 실제 그 점을 인지하지 못하면 버그로 인식할 가능성
* 예외처리 제거하였고 불필요한 import 정리

Fix: 음식명 중복에 대한 예외처리 제거 (#133)

---

src/main/java/com/diareat/diareat/auth/component/JwtAuthFilter.java
src/main/java/com/diareat/diareat/auth/component/JwtTokenProvider.java
src/main/java/com/diareat/diareat/auth/controller/AuthController.java
src/main/java/com/diareat/diareat/auth/dto/ResponseJwtDto.java
src/main/java/com/diareat/diareat/auth/service/CustomUserDetailService.java
src/main/java/com/diareat/diareat/user/service/UserService.java
src/main/java/com/diareat/diareat/util/api/ResponseCode.java

- 단일 JWT 토큰을 AccessToken, RefreshToken으로 이분화
- AccessToken은 1시간으로 단축
- RefreshToken은 Redis에 저장되며, AccessToken 재발급 용도

Feat: JWT AccessToken & RefreshToken 구현

---

src/main/java/com/diareat/diareat/auth/component/JwtTokenProvider.java
src/main/java/com/diareat/diareat/auth/controller/AuthController.java
src/main/java/com/diareat/diareat/util/exception/GlobalExceptionHandler.java
src/main/java/com/diareat/diareat/util/exception/ValidException.java

* JWT accessToken 관련 유효성 판정 일단 T/F 반환 형식으로 유지 (추후 개편예정)
* RefreshToken의 경우에는 유효성 검증 실패 시 401 관련 예외처리 띄우도록 처리

Fix: Jwt 일부 코드 복구 및 RefreshToken 만료 관련 예외처리 반영 (#152)
